
CREATE DATABASE IF NOT EXISTS leash2leash_db;
USE leash2leash_db;


CREATE TABLE IF NOT EXISTS account_info (
id INTEGER (100)AUTO_INCREMENT NOT NULL,
user_name VARCHAR (100) NOT NULL,
user_email VARCHAR (100) NOT NULL,
location VARCHAR (100) NOT NULL,
am_pm VARCHAR (100) NOT NULL,
weekend_weekday VARCHAR (100) NOT NULL,
dog_type VARCHAR (100) NOT NULL,
PRIMARY KEY (id)
);