CREATE DATABASE leash2leash;

USE leash2leash;

CREATE TABLE accountinfo (
id INTEGER (100) AUTO_INCREMENT NOT NULL,
name VARCHAR (100) NOT NULL,
email VARCHAR (100) NOT NULL,
location VARCHAR (100) NOT NULL,
PRIMARY KEY (id) 
);

